name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      
      - name: Add current platform to lockfile
        run: bundle lock --add-platform x86_64-linux
      
      - name: Install dependencies
        run: bundle install
      
      - name: Run RuboCop
        run: bundle exec rake
